// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MasterTest.Models
{
    public partial class Attachments
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public DateTime? UploadedDate { get; set; }
        public byte[] Attachment { get; set; }
        public string FileExtension { get; set; }
    }
}