// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MasterTest.Models
{
    public partial class Business
    {
        public int Id { get; set; }
        public string LegalName { get; set; }
        public string Dbaname { get; set; }
        public int Fein { get; set; }
        public string BusinessType { get; set; }
        public string Address { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? JoinedDate { get; set; }
        public DateTime? LeftDate { get; set; }
    }
}