// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MasterTest.Models
{
    public partial class ConvergeData
    {
        public int Id { get; set; }
        public string BrandId { get; set; }
        public string Cctype { get; set; }
        public string Ccnumber { get; set; }
        public string ApprovalCode { get; set; }
        public string ExpiryDate { get; set; }
        public decimal Amount { get; set; }
        public int Years { get; set; }
        public string AddressOnCard { get; set; }
        public string WhoIsPaying { get; set; }
        public string PhoneNo { get; set; }
    }
}