// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MasterTest.Models
{
    public partial class Dfsauthorization
    {
        public string Id { get; set; }
        public string CaseNo { get; set; }
        public string ClientId { get; set; }
        public string ParentName { get; set; }
        public string ChildName { get; set; }
        public decimal? ApprovedPartRate { get; set; }
        public decimal? ApprovedFullRate { get; set; }
        public int? ApprovedPartDays { get; set; }
        public int? ApprovedFullDays { get; set; }
        public decimal? ParentPortionPartRate { get; set; }
        public decimal? ParentPortionFullRate { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public DateTime? AuthorizationDate { get; set; }
        public DateTime? ApplicationDate { get; set; }
        public string CaseWorkerName { get; set; }
        public int ProviderId { get; set; }
        public int? AttachmentId { get; set; }
    }
}