// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MasterTest.Models
{
    public partial class Expenses
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public DateTime DateSaved { get; set; }
        public string Comments { get; set; }
        public int? CategoryId { get; set; }
        public int? SubCategoryId { get; set; }
    }
}