// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MasterTest.Models
{
    public partial class MasterLink
    {
        public string Type { get; set; }
        public int Link1 { get; set; }
        public int Link2 { get; set; }
        public int Id { get; set; }
    }
}