// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MasterTest.Models
{
    public partial class Provider
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ProviderType { get; set; }
        public int? DfsproviderNumber { get; set; }
    }
}